export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan', ar: 'أفغانستان' },
  { code: 'AL', name: 'Albania', ar: 'ألبانيا' },
  { code: 'DZ', name: 'Algeria', ar: 'الجزائر' },
  { code: 'AD', name: 'Andorra', ar: 'أندورا' },
  { code: 'AO', name: 'Angola', ar: 'أنغولا' },
  { code: 'AG', name: 'Antigua and Barbuda', ar: 'أنتيغوا وبربودا' },
  { code: 'AR', name: 'Argentina', ar: 'الأرجنتين' },
  { code: 'AM', name: 'Armenia', ar: 'أرمينيا' },
  { code: 'AU', name: 'Australia', ar: 'أستراليا' },
  { code: 'AT', name: 'Austria', ar: 'النمسا' },
  { code: 'AZ', name: 'Azerbaijan', ar: 'أذربيجان' },
  { code: 'BS', name: 'Bahamas', ar: 'جزر البهاما' },
  { code: 'BH', name: 'Bahrain', ar: 'البحرين' },
  { code: 'BD', name: 'Bangladesh', ar: 'بنغلاديش' },
  { code: 'BB', name: 'Barbados', ar: 'بربادوس' },
  { code: 'BY', name: 'Belarus', ar: 'بيلاروس' },
  { code: 'BE', name: 'Belgium', ar: 'بلجيكا' },
  { code: 'BZ', name: 'Belize', ar: 'بليز' },
  { code: 'BJ', name: 'Benin', ar: 'بنين' },
  { code: 'BT', name: 'Bhutan', ar: 'بوتان' },
  { code: 'BO', name: 'Bolivia', ar: 'بوليفيا' },
  { code: 'BA', name: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
  { code: 'BW', name: 'Botswana', ar: 'بوتسوانا' },
  { code: 'BR', name: 'Brazil', ar: 'البرازيل' },
  { code: 'BN', name: 'Brunei', ar: 'بروناي' },
  { code: 'BG', name: 'Bulgaria', ar: 'بلغاريا' },
  { code: 'BF', name: 'Burkina Faso', ar: 'بوركينا فاسو' },
  { code: 'BI', name: 'Burundi', ar: 'بوروندي' },
  { code: 'KH', name: 'Cambodia', ar: 'كمبوديا' },
  { code: 'CM', name: 'Cameroon', ar: 'الكاميرون' },
  { code: 'CA', name: 'Canada', ar: 'كندا' },
  { code: 'CV', name: 'Cape Verde', ar: 'الرأس الأخضر' },
  { code: 'CF', name: 'Central African Republic', ar: 'جمهورية أفريقيا الوسطى' },
  { code: 'TD', name: 'Chad', ar: 'تشاد' },
  { code: 'CL', name: 'Chile', ar: 'تشيلي' },
  { code: 'CN', name: 'China', ar: 'الصين' },
  { code: 'CO', name: 'Colombia', ar: 'كولومبيا' },
  { code: 'KM', name: 'Comoros', ar: 'جزر القمر' },
  { code: 'CG', name: 'Congo', ar: 'الكونغو' },
  { code: 'CR', name: 'Costa Rica', ar: 'كوستاريكا' },
  { code: 'HR', name: 'Croatia', ar: 'كرواتيا' },
  { code: 'CU', name: 'Cuba', ar: 'كوبا' },
  { code: 'CY', name: 'Cyprus', ar: 'قبرص' },
  { code: 'CZ', name: 'Czech Republic', ar: 'جمهورية التشيك' },
  { code: 'DK', name: 'Denmark', ar: 'الدنمارك' },
  { code: 'DJ', name: 'Djibouti', ar: 'جيبوتي' },
  { code: 'DM', name: 'Dominica', ar: 'دومينيكا' },
  { code: 'DO', name: 'Dominican Republic', ar: 'جمهورية الدومينيكان' },
  { code: 'EC', name: 'Ecuador', ar: 'الإكوادور' },
  { code: 'EG', name: 'Egypt', ar: 'مصر' },
  { code: 'SV', name: 'El Salvador', ar: 'السلفادور' },
  { code: 'GQ', name: 'Equatorial Guinea', ar: 'غينيا الاستوائية' },
  { code: 'ER', name: 'Eritrea', ar: 'إريتريا' },
  { code: 'EE', name: 'Estonia', ar: 'إستونيا' },
  { code: 'ET', name: 'Ethiopia', ar: 'إثيوبيا' },
  { code: 'FJ', name: 'Fiji', ar: 'فيجي' },
  { code: 'FI', name: 'Finland', ar: 'فنلندا' },
  { code: 'FR', name: 'France', ar: 'فرنسا' },
  { code: 'GA', name: 'Gabon', ar: 'الجابون' },
  { code: 'GM', name: 'Gambia', ar: 'غامبيا' },
  { code: 'GE', name: 'Georgia', ar: 'جورجيا' },
  { code: 'DE', name: 'Germany', ar: 'ألمانيا' },
  { code: 'GH', name: 'Ghana', ar: 'غانا' },
  { code: 'GR', name: 'Greece', ar: 'اليونان' },
  { code: 'GD', name: 'Grenada', ar: 'غرينادا' },
  { code: 'GT', name: 'Guatemala', ar: 'غواتيمالا' },
  { code: 'GN', name: 'Guinea', ar: 'غينيا' },
  { code: 'GW', name: 'Guinea-Bissau', ar: 'غينيا بيساو' },
  { code: 'GY', name: 'Guyana', ar: 'غيانا' },
  { code: 'HT', name: 'Haiti', ar: 'هايتي' },
  { code: 'HN', name: 'Honduras', ar: 'هندوراس' },
  { code: 'HU', name: 'Hungary', ar: 'المجر' },
  { code: 'IS', name: 'Iceland', ar: 'آيسلندا' },
  { code: 'IN', name: 'India', ar: 'الهند' },
  { code: 'ID', name: 'Indonesia', ar: 'إندونيسيا' },
  { code: 'IR', name: 'Iran', ar: 'إيران' },
  { code: 'IQ', name: 'Iraq', ar: 'العراق' },
  { code: 'IE', name: 'Ireland', ar: 'أيرلندا' },
  { code: 'IL', name: 'Israel', ar: 'إسرائيل' },
  { code: 'IT', name: 'Italy', ar: 'إيطاليا' },
  { code: 'CI', name: 'Ivory Coast', ar: 'ساحل العاج' },
  { code: 'JM', name: 'Jamaica', ar: 'جامايكا' },
  { code: 'JP', name: 'Japan', ar: 'اليابان' },
  { code: 'JO', name: 'Jordan', ar: 'الأردن' },
  { code: 'KZ', name: 'Kazakhstan', ar: 'كازاخستان' },
  { code: 'KE', name: 'Kenya', ar: 'كينيا' },
  { code: 'KI', name: 'Kiribati', ar: 'كيريباتي' },
  { code: 'KP', name: 'North Korea', ar: 'كوريا الشمالية' },
  { code: 'KR', name: 'South Korea', ar: 'كوريا الجنوبية' },
  { code: 'KW', name: 'Kuwait', ar: 'الكويت' },
  { code: 'KG', name: 'Kyrgyzstan', ar: 'قيرغيزستان' },
  { code: 'LA', name: 'Laos', ar: 'لاوس' },
  { code: 'LV', name: 'Latvia', ar: 'لاتفيا' },
  { code: 'LB', name: 'Lebanon', ar: 'لبنان' },
  { code: 'LS', name: 'Lesotho', ar: 'ليسوتو' },
  { code: 'LR', name: 'Liberia', ar: 'ليبيريا' },
  { code: 'LY', name: 'Libya', ar: 'ليبيا' },
  { code: 'LI', name: 'Liechtenstein', ar: 'ليختنشتاين' },
  { code: 'LT', name: 'Lithuania', ar: 'ليتوانيا' },
  { code: 'LU', name: 'Luxembourg', ar: 'لوكسمبرغ' },
  { code: 'MG', name: 'Madagascar', ar: 'مدغشقر' },
  { code: 'MW', name: 'Malawi', ar: 'ملاوي' },
  { code: 'MY', name: 'Malaysia', ar: 'ماليزيا' },
  { code: 'MV', name: 'Maldives', ar: 'جزر المالديف' },
  { code: 'ML', name: 'Mali', ar: 'مالي' },
  { code: 'MT', name: 'Malta', ar: 'مالطا' },
  { code: 'MH', name: 'Marshall Islands', ar: 'جزر مارشال' },
  { code: 'MR', name: 'Mauritania', ar: 'موريتانيا' },
  { code: 'MU', name: 'Mauritius', ar: 'موريشيوس' },
  { code: 'MX', name: 'Mexico', ar: 'المكسيك' },
  { code: 'FM', name: 'Micronesia', ar: 'ميكرونيزيا' },
  { code: 'MD', name: 'Moldova', ar: 'مولدوفا' },
  { code: 'MC', name: 'Monaco', ar: 'موناكو' },
  { code: 'MN', name: 'Mongolia', ar: 'منغوليا' },
  { code: 'ME', name: 'Montenegro', ar: 'الجبل الأسود' },
  { code: 'MA', name: 'Morocco', ar: 'المغرب' },
  { code: 'MZ', name: 'Mozambique', ar: 'موزمبيق' },
  { code: 'MM', name: 'Myanmar', ar: 'ميانمار' },
  { code: 'NA', name: 'Namibia', ar: 'ناميبيا' },
  { code: 'NR', name: 'Nauru', ar: 'ناورو' },
  { code: 'NP', name: 'Nepal', ar: 'نيبال' },
  { code: 'NL', name: 'Netherlands', ar: 'هولندا' },
  { code: 'NZ', name: 'New Zealand', ar: 'نيوزيلندا' },
  { code: 'NI', name: 'Nicaragua', ar: 'نيكاراغوا' },
  { code: 'NE', name: 'Niger', ar: 'النيجر' },
  { code: 'NG', name: 'Nigeria', ar: 'نيجيريا' },
  { code: 'NO', name: 'Norway', ar: 'النرويج' },
  { code: 'OM', name: 'Oman', ar: 'عمان' },
  { code: 'PK', name: 'Pakistan', ar: 'باكستان' },
  { code: 'PW', name: 'Palau', ar: 'بالاو' },
  { code: 'PS', name: 'Palestine', ar: 'فلسطين' },
  { code: 'PA', name: 'Panama', ar: 'بنما' },
  { code: 'PG', name: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' },
  { code: 'PY', name: 'Paraguay', ar: 'باراغواي' },
  { code: 'PE', name: 'Peru', ar: 'بيرو' },
  { code: 'PH', name: 'Philippines', ar: 'الفلبين' },
  { code: 'PL', name: 'Poland', ar: 'بولندا' },
  { code: 'PT', name: 'Portugal', ar: 'البرتغال' },
  { code: 'QA', name: 'Qatar', ar: 'قطر' },
  { code: 'RO', name: 'Romania', ar: 'رومانيا' },
  { code: 'RU', name: 'Russia', ar: 'روسيا' },
  { code: 'RW', name: 'Rwanda', ar: 'رواندا' },
  { code: 'KN', name: 'Saint Kitts and Nevis', ar: 'سانت كيتس ونيفس' },
  { code: 'LC', name: 'Saint Lucia', ar: 'سانت لوسيا' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', ar: 'سانت فنسنت والجرينادين' },
  { code: 'WS', name: 'Samoa', ar: 'ساموا' },
  { code: 'SM', name: 'San Marino', ar: 'سان مارينو' },
  { code: 'ST', name: 'Sao Tome and Principe', ar: 'سان تومي وبرينسيبي' },
  { code: 'SA', name: 'Saudi Arabia', ar: 'المملكة العربية السعودية' },
  { code: 'SN', name: 'Senegal', ar: 'السنغال' },
  { code: 'RS', name: 'Serbia', ar: 'صربيا' },
  { code: 'SC', name: 'Seychelles', ar: 'سيشل' },
  { code: 'SL', name: 'Sierra Leone', ar: 'سيراليون' },
  { code: 'SG', name: 'Singapore', ar: 'سنغافورة' },
  { code: 'SK', name: 'Slovakia', ar: 'سلوفاكيا' },
  { code: 'SI', name: 'Slovenia', ar: 'سلوفينيا' },
  { code: 'SB', name: 'Solomon Islands', ar: 'جزر سليمان' },
  { code: 'SO', name: 'Somalia', ar: 'الصومال' },
  { code: 'ZA', name: 'South Africa', ar: 'جنوب أفريقيا' },
  { code: 'SS', name: 'South Sudan', ar: 'جنوب السودان' },
  { code: 'ES', name: 'Spain', ar: 'إسبانيا' },
  { code: 'LK', name: 'Sri Lanka', ar: 'سريلانكا' },
  { code: 'SD', name: 'Sudan', ar: 'السودان' },
  { code: 'SR', name: 'Suriname', ar: 'سورينام' },
  { code: 'SE', name: 'Sweden', ar: 'السويد' },
  { code: 'CH', name: 'Switzerland', ar: 'سويسرا' },
  { code: 'SY', name: 'Syria', ar: 'سوريا' },
  { code: 'TW', name: 'Taiwan', ar: 'تايوان' },
  { code: 'TJ', name: 'Tajikistan', ar: 'طاجيكستان' },
  { code: 'TZ', name: 'Tanzania', ar: 'تنزانيا' },
  { code: 'TH', name: 'Thailand', ar: 'تايلاند' },
  { code: 'TL', name: 'Timor-Leste', ar: 'تيمور الشرقية' },
  { code: 'TG', name: 'Togo', ar: 'توغو' },
  { code: 'TO', name: 'Tonga', ar: 'تونغا' },
  { code: 'TT', name: 'Trinidad and Tobago', ar: 'ترينيداد وتوباغو' },
  { code: 'TN', name: 'Tunisia', ar: 'تونس' },
  { code: 'TR', name: 'Turkey', ar: 'تركيا' },
  { code: 'TM', name: 'Turkmenistan', ar: 'تركمانستان' },
  { code: 'TV', name: 'Tuvalu', ar: 'توفالو' },
  { code: 'UG', name: 'Uganda', ar: 'أوغندا' },
  { code: 'UA', name: 'Ukraine', ar: 'أوكرانيا' },
  { code: 'AE', name: 'United Arab Emirates', ar: 'الإمارات العربية المتحدة' },
  { code: 'GB', name: 'United Kingdom', ar: 'المملكة المتحدة' },
  { code: 'US', name: 'United States', ar: 'الولايات المتحدة' },
  { code: 'UY', name: 'Uruguay', ar: 'أوروغواي' },
  { code: 'UZ', name: 'Uzbekistan', ar: 'أوزبكستان' },
  { code: 'VU', name: 'Vanuatu', ar: 'فانواتو' },
  { code: 'VA', name: 'Vatican City', ar: 'مدينة الفاتيكان' },
  { code: 'VE', name: 'Venezuela', ar: 'فنزويلا' },
  { code: 'VN', name: 'Vietnam', ar: 'فيتنام' },
  { code: 'YE', name: 'Yemen', ar: 'اليمن' },
  { code: 'ZM', name: 'Zambia', ar: 'زامبيا' },
  { code: 'ZW', name: 'Zimbabwe', ar: 'زيمبابوي' },
];
