-- Create countries table
CREATE TABLE IF NOT EXISTS countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code VARCHAR(2) UNIQUE NOT NULL,
  name_en VARCHAR(255) NOT NULL,
  name_ar VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_countries_code ON countries(code);
CREATE INDEX IF NOT EXISTS idx_countries_name_en ON countries(name_en);
CREATE INDEX IF NOT EXISTS idx_countries_name_ar ON countries(name_ar);

-- Insert all countries
INSERT INTO countries (code, name_en, name_ar) VALUES
('AF', 'Afghanistan', 'أفغانستان'),
('AL', 'Albania', 'ألبانيا'),
('DZ', 'Algeria', 'الجزائر'),
('AD', 'Andorra', 'أندورا'),
('AO', 'Angola', 'أنغولا'),
('AG', 'Antigua and Barbuda', 'أنتيغوا وبربودا'),
('AR', 'Argentina', 'الأرجنتين'),
('AM', 'Armenia', 'أرمينيا'),
('AU', 'Australia', 'أستراليا'),
('AT', 'Austria', 'النمسا'),
('AZ', 'Azerbaijan', 'أذربيجان'),
('BS', 'Bahamas', 'جزر البهاما'),
('BH', 'Bahrain', 'البحرين'),
('BD', 'Bangladesh', 'بنغلاديش'),
('BB', 'Barbados', 'بربادوس'),
('BY', 'Belarus', 'بيلاروس'),
('BE', 'Belgium', 'بلجيكا'),
('BZ', 'Belize', 'بليز'),
('BJ', 'Benin', 'بنين'),
('BT', 'Bhutan', 'بوتان'),
('BO', 'Bolivia', 'بوليفيا'),
('BA', 'Bosnia and Herzegovina', 'البوسنة والهرسك'),
('BW', 'Botswana', 'بوتسوانا'),
('BR', 'Brazil', 'البرازيل'),
('BN', 'Brunei', 'بروناي'),
('BG', 'Bulgaria', 'بلغاريا'),
('BF', 'Burkina Faso', 'بوركينا فاسو'),
('BI', 'Burundi', 'بوروندي'),
('KH', 'Cambodia', 'كمبوديا'),
('CM', 'Cameroon', 'الكاميرون'),
('CA', 'Canada', 'كندا'),
('CV', 'Cape Verde', 'الرأس الأخضر'),
('CF', 'Central African Republic', 'جمهورية أفريقيا الوسطى'),
('TD', 'Chad', 'تشاد'),
('CL', 'Chile', 'تشيلي'),
('CN', 'China', 'الصين'),
('CO', 'Colombia', 'كولومبيا'),
('KM', 'Comoros', 'جزر القمر'),
('CG', 'Congo', 'الكونغو'),
('CR', 'Costa Rica', 'كوستاريكا'),
('HR', 'Croatia', 'كرواتيا'),
('CU', 'Cuba', 'كوبا'),
('CY', 'Cyprus', 'قبرص'),
('CZ', 'Czech Republic', 'جمهورية التشيك'),
('DK', 'Denmark', 'الدنمارك'),
('DJ', 'Djibouti', 'جيبوتي'),
('DM', 'Dominica', 'دومينيكا'),
('DO', 'Dominican Republic', 'جمهورية الدومينيكان'),
('EC', 'Ecuador', 'الإكوادور'),
('EG', 'Egypt', 'مصر'),
('SV', 'El Salvador', 'السلفادور'),
('GQ', 'Equatorial Guinea', 'غينيا الاستوائية'),
('ER', 'Eritrea', 'إريتريا'),
('EE', 'Estonia', 'إستونيا'),
('ET', 'Ethiopia', 'إثيوبيا'),
('FJ', 'Fiji', 'فيجي'),
('FI', 'Finland', 'فنلندا'),
('FR', 'France', 'فرنسا'),
('GA', 'Gabon', 'الجابون'),
('GM', 'Gambia', 'غامبيا'),
('GE', 'Georgia', 'جورجيا'),
('DE', 'Germany', 'ألمانيا'),
('GH', 'Ghana', 'غانا'),
('GR', 'Greece', 'اليونان'),
('GD', 'Grenada', 'غرينادا'),
('GT', 'Guatemala', 'غواتيمالا'),
('GN', 'Guinea', 'غينيا'),
('GW', 'Guinea-Bissau', 'غينيا بيساو'),
('GY', 'Guyana', 'غيانا'),
('HT', 'Haiti', 'هايتي'),
('HN', 'Honduras', 'هندوراس'),
('HU', 'Hungary', 'المجر'),
('IS', 'Iceland', 'آيسلندا'),
('IN', 'India', 'الهند'),
('ID', 'Indonesia', 'إندونيسيا'),
('IR', 'Iran', 'إيران'),
('IQ', 'Iraq', 'العراق'),
('IE', 'Ireland', 'أيرلندا'),
('IL', 'Israel', 'إسرائيل'),
('IT', 'Italy', 'إيطاليا'),
('CI', 'Ivory Coast', 'ساحل العاج'),
('JM', 'Jamaica', 'جامايكا'),
('JP', 'Japan', 'اليابان'),
('JO', 'Jordan', 'الأردن'),
('KZ', 'Kazakhstan', 'كازاخستان'),
('KE', 'Kenya', 'كينيا'),
('KI', 'Kiribati', 'كيريباتي'),
('KP', 'North Korea', 'كوريا الشمالية'),
('KR', 'South Korea', 'كوريا الجنوبية'),
('KW', 'Kuwait', 'الكويت'),
('KG', 'Kyrgyzstan', 'قيرغيزستان'),
('LA', 'Laos', 'لاوس'),
('LV', 'Latvia', 'لاتفيا'),
('LB', 'Lebanon', 'لبنان'),
('LS', 'Lesotho', 'ليسوتو'),
('LR', 'Liberia', 'ليبيريا'),
('LY', 'Libya', 'ليبيا'),
('LI', 'Liechtenstein', 'ليختنشتاين'),
('LT', 'Lithuania', 'ليتوانيا'),
('LU', 'Luxembourg', 'لوكسمبرغ'),
('MG', 'Madagascar', 'مدغشقر'),
('MW', 'Malawi', 'ملاوي'),
('MY', 'Malaysia', 'ماليزيا'),
('MV', 'Maldives', 'جزر المالديف'),
('ML', 'Mali', 'مالي'),
('MT', 'Malta', 'مالطا'),
('MH', 'Marshall Islands', 'جزر مارشال'),
('MR', 'Mauritania', 'موريتانيا'),
('MU', 'Mauritius', 'موريشيوس'),
('MX', 'Mexico', 'المكسيك'),
('FM', 'Micronesia', 'ميكرونيزيا'),
('MD', 'Moldova', 'مولدوفا'),
('MC', 'Monaco', 'موناكو'),
('MN', 'Mongolia', 'منغوليا'),
('ME', 'Montenegro', 'الجبل الأسود'),
('MA', 'Morocco', 'المغرب'),
('MZ', 'Mozambique', 'موزمبيق'),
('MM', 'Myanmar', 'ميانمار'),
('NA', 'Namibia', 'ناميبيا'),
('NR', 'Nauru', 'ناورو'),
('NP', 'Nepal', 'نيبال'),
('NL', 'Netherlands', 'هولندا'),
('NZ', 'New Zealand', 'نيوزيلندا'),
('NI', 'Nicaragua', 'نيكاراغوا'),
('NE', 'Niger', 'النيجر'),
('NG', 'Nigeria', 'نيجيريا'),
('NO', 'Norway', 'النرويج'),
('OM', 'Oman', 'عمان'),
('PK', 'Pakistan', 'باكستان'),
('PW', 'Palau', 'بالاو'),
('PS', 'Palestine', 'فلسطين'),
('PA', 'Panama', 'بنما'),
('PG', 'Papua New Guinea', 'بابوا غينيا الجديدة'),
('PY', 'Paraguay', 'باراغواي'),
('PE', 'Peru', 'بيرو'),
('PH', 'Philippines', 'الفلبين'),
('PL', 'Poland', 'بولندا'),
('PT', 'Portugal', 'البرتغال'),
('QA', 'Qatar', 'قطر'),
('RO', 'Romania', 'رومانيا'),
('RU', 'Russia', 'روسيا'),
('RW', 'Rwanda', 'رواندا'),
('KN', 'Saint Kitts and Nevis', 'سانت كيتس ونيفس'),
('LC', 'Saint Lucia', 'سانت لوسيا'),
('VC', 'Saint Vincent and the Grenadines', 'سانت فنسنت والجرينادين'),
('WS', 'Samoa', 'ساموا'),
('SM', 'San Marino', 'سان مارينو'),
('ST', 'Sao Tome and Principe', 'سان تومي وبرينسيبي'),
('SA', 'Saudi Arabia', 'المملكة العربية السعودية'),
('SN', 'Senegal', 'السنغال'),
('RS', 'Serbia', 'صربيا'),
('SC', 'Seychelles', 'سيشل'),
('SL', 'Sierra Leone', 'سيراليون'),
('SG', 'Singapore', 'سنغافورة'),
('SK', 'Slovakia', 'سلوفاكيا'),
('SI', 'Slovenia', 'سلوفينيا'),
('SB', 'Solomon Islands', 'جزر سليمان'),
('SO', 'Somalia', 'الصومال'),
('ZA', 'South Africa', 'جنوب أفريقيا'),
('SS', 'South Sudan', 'جنوب السودان'),
('ES', 'Spain', 'إسبانيا'),
('LK', 'Sri Lanka', 'سريلانكا'),
('SD', 'Sudan', 'السودان'),
('SR', 'Suriname', 'سورينام'),
('SE', 'Sweden', 'السويد'),
('CH', 'Switzerland', 'سويسرا'),
('SY', 'Syria', 'سوريا'),
('TW', 'Taiwan', 'تايوان'),
('TJ', 'Tajikistan', 'طاجيكستان'),
('TZ', 'Tanzania', 'تنزانيا'),
('TH', 'Thailand', 'تايلاند'),
('TL', 'Timor-Leste', 'تيمور الشرقية'),
('TG', 'Togo', 'توغو'),
('TO', 'Tonga', 'تونغا'),
('TT', 'Trinidad and Tobago', 'ترينيداد وتوباغو'),
('TN', 'Tunisia', 'تونس'),
('TR', 'Turkey', 'تركيا'),
('TM', 'Turkmenistan', 'تركمانستان'),
('TV', 'Tuvalu', 'توفالو'),
('UG', 'Uganda', 'أوغندا'),
('UA', 'Ukraine', 'أوكرانيا'),
('AE', 'United Arab Emirates', 'الإمارات العربية المتحدة'),
('GB', 'United Kingdom', 'المملكة المتحدة'),
('US', 'United States', 'الولايات المتحدة'),
('UY', 'Uruguay', 'أوروغواي'),
('UZ', 'Uzbekistan', 'أوزبكستان'),
('VU', 'Vanuatu', 'فانواتو'),
('VA', 'Vatican City', 'مدينة الفاتيكان'),
('VE', 'Venezuela', 'فنزويلا'),
('VN', 'Vietnam', 'فيتنام'),
('YE', 'Yemen', 'اليمن'),
('ZM', 'Zambia', 'زامبيا'),
('ZW', 'Zimbabwe', 'زيمبابوي')
ON CONFLICT (code) DO NOTHING;
